version: '3.4'

x-app:
  &app
  build:
    context: .
    dockerfile: Dockerfile.dev
  environment:
    RAILS_ENV: development
    DB_USERNAME: postgres
    DB_PASSWORD: secret
    DB_HOST: db
    DB_PORT: 5432
    DB_NAME: narnia_db
    SECRET_KEY_BASE: STUB
    REDIS_URL: redis://redis:6379/1
  stdin_open: true
  tty: true
  volumes:
    - .:/app
    - bundle_cache:/bundle

services:
  api:
    <<: *app
    ports:
      - 3000:3000/tcp
    depends_on:
      - db

  db:
    image: postgres:11.2
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    restart: always
    volumes:
      - postgres:/var/lib/postgresql/data

  sidekiq:
    <<: *app
    command: bundle exec sidekiq
    depends_on:
      - redis
      - api

  redis:
    image: 'redis:5.0-alpine'
    command: redis-server
    volumes:
      - redis:/data

volumes:
  bundle_cache:
  postgres:
  redis:
